---

  - block:

      - name: WireGuard | Dependencies
        apt:
          name:
            - linux-headers-generic
        become: yes
        tags:
          - wireguard

      - name : WireGuard | Add repo for Debian
        apt_repository:
          repo: deb http://deb.debian.org/debian/ unstable main
          state: present
          filename: unstable-wireguard.list
          update_cache: yes
        when: ansible_distribution == 'Debian'
        become: yes
        tags:
          - wireguard

      - name: WireGuard | allow apt to use unstable Debian
        copy:
          src: limit-unstable
          dest: /etc/apt/preferences.d/limit-unstable
        when: ansible_distribution == 'Debian' and option_allow_unstable_on_debian
        become: yes
        tags:
          - wireguard

      - name: WireGuard | Add PPA for ubuntu
        apt_repository:
          repo: 'ppa:wireguard/wireguard'
        become: yes
        when: ansible_distribution == 'Ubuntu
        tags:
          - wireguard

      - name: WireGuard | install
        apt:
          name:
            - wireguard-dkms
            - wireguard-tools
        state: present
        update_cache: true
        become: yes
        tags:
          - wireguard     

    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

  - block:

    - name: WireGuard | Epel
      include_tasks: sa-epel/main.yml
      tags:
        - wireguard     

    - name: WireGuard | install Kernel devel
      yum:
        name: kernel-devel
        state: present
      become: yes
      tags:
        - wireguard

    - name: WireGuard | add repo for CentOS/RHEL 7
      get_url:
        url: "{{ wg_epel_repo }}"
        dest: /etc/yum.repos.d/wireguard.repo
      become: yes
      tags:
        - wireguard

    - name: WireGuard | install
      package:
        name:
          - wireguard-dkms
          - wireguard-tools
      state: present
      become: yes
      tags:
        - wireguard     

    when: ansible_distribution in [ "CentOS", "RedHat" ]

  - name: WireGuard | Check server config provisioned
    stat:
      path: /etc/wireguard/wg0.conf
    register: server_config_provisioned
    become: yes
    tags:
      - wireguard     

  - name: WireGuard | Generate private and public keys for server
    shell: umask 077; wg genkey | tee server.private | wg pubkey > server.public
    args:
      chdir: /etc/wireguard
    register: server_key_file
    when: server_config_provisioned.stat.exists == false
    become: yes
    tags:
      - wireguard

  - name: Register WireGuard private key as a variable
    slurp:
      src: /etc/wireguard/server.private
    register: wg_privatekey

  - debug: var="wg_privatekey"

  - name: WireGuard | Generate private and public keys for users  
    shell: umask 077; wg genkey | tee {{ item.name }}.private | wg pubkey > {{ item.name }}.public
    args:
      chdir: /etc/wireguard
      creates: "/etc/wireguard/{{ item.name }}.private"
    become: yes
    tags:
      - wireguard     
   
  - name: WireGuard | Stop service (1/2)
    service:
      name: wg-quick@wg0.service
      state: stopped
    ignore_errors: true  
    become: yes
    tags:
      - wireguard

  - name: WireGuard | Stop service (2/2)
    command: wg-quick down wg0
    ignore_errors: true  
    become: yes
    tags:
      - wireguard

  - name: WireGuard | template server config
    template:
      src: "templates/wg0.conf.j2"
      dest: "/etc/wireguard/wg0.conf"
      owner: root
      group: root
      mode: 0600
    become: yes
    tags:
      - wireguard

  - name: WireGuard | Start service
    service:
      name: wg-quick@wg0
      enabled: yes
      state: started
    become: yes
    tags:
      - wireguard


- name: Register the clients on the vpn server
  shell: "wg set wg0 peer {{ item.public_key }}"
  with_items: "{{users | default([])}}"

- name: Restart the VPN service to save changes
  service:
    name: wg-quick@wg0.service
    state: restarted
  become: yes
  tags:
    - wireguard
